### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Skillgjii** [qbcore-framework/qb-apartments#58]
**Describe the bug**
If i logout inside the apartments, then when we log back inn, we 9/10 times go into the wrong routing bucket when leaving for the outside, resulting that the player cant se anybody else on the server.

**Comment by rhapidfyre** [comment]
Also just had this issue on our server as well.

Repro:
Exit your apartment, re-enter the apartment, go to the logout point, log out. Switch to a character who is not in an instance/interior.

**Comment by TakeFiveGames** [comment]
I fixed this on my server by doing the following in `client.main`:

```
RegisterNetEvent('QBCore:Client:OnPlayerUnload', function()
    exports['qb-interior']:DespawnInterior(houseObj, function()
      TriggerEvent('qb-weathersync:client:EnableSync')
	end)
    CurrentApartment = nil
    InApartment = false
    CurrentOffset = 0
end)
```
Basically the idea of the code, whether it actually works or not, is that by unloading, players will trigger qb-interior to despawn the house interior (apartment), if loaded. Sets the current apartment to nil, and resets.

Since adding that snippet, players haven't been having this issue.

**Comment by Muri22** [comment]
have the same issue 
![Capture](https://user-images.githubusercontent.com/88394932/165871236-073c6f44-11f9-4582-939f-24f35b232430.PNG)

**Comment by erikmeyer08** [comment]
Having the same issue as well.

**Comment by nzkfc** [comment]
@Skillgjii this still an issue?

**Comment by amantu-qbit** [comment]
Looks like this is solved
